"""
LegalEase AI - PDF Generator
==============================
Generates downloadable consumer guidance reports using reportlab.
"""

from io import BytesIO
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, ListFlowable, ListItem

from app.models.application_models import Report


class PDFGenerator:
    @staticmethod
    def generate_report_pdf(report: Report) -> bytes:
        """Generate a PDF document from a Report model."""
        buffer = BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            rightMargin=50,
            leftMargin=50,
            topMargin=50,
            bottomMargin=50,
            title="LegalEase AI - Consumer Guidance Report"
        )

        styles = getSampleStyleSheet()
        styles.add(ParagraphStyle(name="ReportTitle", parent=styles["Heading1"], spaceAfter=20, textColor=colors.HexColor("#1e3a8a")))
        styles.add(ParagraphStyle(name="SectionTitle", parent=styles["Heading2"], spaceBefore=15, spaceAfter=10, textColor=colors.HexColor("#2563eb")))
        styles.add(ParagraphStyle(name="NormalText", parent=styles["Normal"], spaceAfter=8, leading=14))

        elements = []

        # Title
        elements.append(Paragraph("Consumer Guidance Report", styles["ReportTitle"]))
        elements.append(Paragraph(f"Generated by LegalEase AI | Case ID: {report.case_id}", styles["NormalText"]))
        elements.append(Spacer(1, 20))

        # Case Summary
        elements.append(Paragraph("1. Case Summary", styles["SectionTitle"]))
        elements.append(Paragraph(report.case_summary, styles["NormalText"]))
        elements.append(Spacer(1, 10))

        # Consumer Rights
        elements.append(Paragraph("2. Applicable Consumer Rights", styles["SectionTitle"]))
        for right in report.consumer_rights:
            text = f"<b>{right['right']}</b>: {right['description']} <i>(Citation: {right['legal_citation']})</i>"
            elements.append(Paragraph(text, styles["NormalText"]))
        elements.append(Spacer(1, 10))

        # Resolution Roadmap
        elements.append(Paragraph("3. Resolution Roadmap", styles["SectionTitle"]))
        roadmap_items = []
        for step in sorted(report.roadmap_steps, key=lambda x: x["step_number"]):
            text = f"<b>Step {step['step_number']}: {step['title']}</b> - {step['description']}"
            roadmap_items.append(ListItem(Paragraph(text, styles["NormalText"])))
        elements.append(ListFlowable(roadmap_items, bulletType="bullet", start="square"))
        elements.append(Spacer(1, 10))

        # Evidence Checklist
        elements.append(Paragraph("4. Evidence Checklist", styles["SectionTitle"]))
        evidence_items = []
        for ev in report.evidence_items:
            req_str = "Required" if ev["is_required"] else "Optional"
            text = f"<b>{ev['item']} ({req_str})</b>: {ev['description']}"
            evidence_items.append(ListItem(Paragraph(text, styles["NormalText"])))
        elements.append(ListFlowable(evidence_items, bulletType="bullet", start="square"))
        elements.append(Spacer(1, 10))

        # Next Steps
        elements.append(Paragraph("5. Recommended Next Steps", styles["SectionTitle"]))
        elements.append(Paragraph(report.next_steps, styles["NormalText"]))
        elements.append(Spacer(1, 10))

        # Authority
        elements.append(Paragraph("6. Suggested Authority", styles["SectionTitle"]))
        elements.append(Paragraph(report.recommended_authority, styles["NormalText"]))

        # Build PDF
        doc.build(elements)
        pdf_bytes = buffer.getvalue()
        buffer.close()
        
        return pdf_bytes
